wip: only build versions that dont exist on dist
ipfs/distributions pull request #320
Opened 2020-10-23 11:16 UTC by olizilla

This PR will rework things to only build binaries that aren't already published on dist.ipfs.io.

The releases dir will be patched into the exiting CID for dist.ipfs.io to create the new site.

I assert that this will work and be rad because content-addressing.

Also of note, this is a someewhat of a pre-requisite for #273 so we can start building dist in CI, and get binaries signed without requiring everyone to own apple hardware. On the default branch building dist takes about 25GB of disk and about 2hrs on a Quad-Core i7. It doesn't need to if we trust in the hashes.

TODO:
- [x] only build what changed
- [ ] fix website generation to not depend on a complete local releases dir
- [ ] fix publishing to patch new release into existing dist.ipfs.io CID

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

2020-10-27 16:53 UTC, olizilla commented on build-go.sh
> +	local versions="$1"
The list of versions that need building is now calculated during the build, so we change this to expect a list rather than a file name.

2020-10-27 16:54 UTC, olizilla commented on build-go.sh
> +	newVersions=$(comm -13 <(ipfs cat "$existing/$distname/versions") "$versions")
I should add a check to see if `ipfs` exists and the deamon is online.

2020-10-27 16:56 UTC, olizilla commented on build-go.sh
> +	cp "$versions" "$outputDir/versions"
Moved the _copy the versions file_ step here so we only copy it if it changed.

2020-10-27 16:57 UTC, olizilla commented on package.json
> +    "standard": "standard scripts/*.js site/assets/js/*.js",
extracted to it's own script so we can run `npm run standard -- --fix` and have it auto fix the lints.

2020-10-27 16:57 UTC, olizilla commented on package.json
> +    "clean": "rm -rf site/static/*.js site/static/*.css site/data/releases",
the `dist` target adds data files to `site/data/releases` but `clean` wasn't cleaning it, so now it does.

2020-10-27 17:01 UTC, olizilla commented on scripts/dist.js
> +
and the build process will now only have dist.json files for the dists that are chaning, (typically 1 at time) so it pulls the others from the existing dist.ipfs.io... it's pulling them from the gateway, but I could update this to use `ipfs-http-client` and the local IPFS node as is done in `./scripts/patch.js`

2020-10-27 17:07 UTC, olizilla commented
I know the dist build process could be alot nicer. This is first adventure in there, so my goal here was not to change any more than necessary to get patch style build/publish working. I over-stepped that, but not by much, the core of the build process is left unchanged.

@aschmahmann we should step through this together when you have time.
@dignifiedquire if you have a moment to sanity check this then that would be rad. If not, no worries!

2020-10-28 10:21 UTC, olizilla commented on scripts/dist.js
> +
- ✅ Updated to use ipfs rather than the gateway to fetch published dist.json

2020-10-28 10:29 UTC, dignifiedquire approved these changes
looks sane to me 👍

2020-10-28 11:06 UTC, olizilla commented on build-go.sh
> +	newVersions=$(comm -13 <(ipfs cat "$existing/$distname/versions") "$versions")
Added a check to deps-check.sh and updated it so we check it early and halt the build if any are missing in https://github.com/ipfs/distributions/pull/320/commits/3398a234ce493f8fa780a3873e2d5b222e1bbfee

2020-10-28 12:04 UTC, olizilla commented
@lidel do these changes bring you joy?

2020-10-28 17:02 UTC, lidel requested changes
Removing the need for fetching entire thing brings joy! :heart: :raised_hands: 

But I think we need to make it more self-contained and reproducible.

Found some issues while trying to run `make publish` locally (fresh `git clone`)

## a bug while fetching `dist.json`

Without it `JSON.parse` got invalid input and failed like this:

```
> dist.ipfs.io@1.0.0 build /home/lidel/project/ipfs/distributions
> npm run dist && npm run build:assets && npm run build:hugo


> dist.ipfs.io@1.0.0 dist /home/lidel/project/ipfs/distributions
> node scripts/dist.js

Updating hugo data for dist website
- Fetching dist.json for fs-repo-migrations v1.6.4 from /ipns/dist.ipfs.io
- Fetching dist.json for go-ipfs v0.7.0 from /ipns/dist.ipfs.io
- Fetching dist.json for gx v0.14.2 from /ipns/dist.ipfs.io
- Fetching dist.json for gx-go v1.9.0 from /ipns/dist.ipfs.io
- Fetching dist.json for ipfs-cluster-ctl v0.13.0 from /ipns/dist.ipfs.io
SyntaxError: Unexpected token , in JSON at position 3670
    at JSON.parse (<anonymous>)
    at fetchDistData (/home/lidel/project/ipfs/distributions/scripts/dist.js:44:21)
```

Perhaps we need `concat` instead of `all`?

```diff
-const all = require('it-all')
+const concat = require('it-concat')
-    jsonStr = await all(ipfs.cat(`${DIST_ROOT}/${distName}/${version}/dist.json`))
+    jsonStr = await concat(ipfs.cat(`${DIST_ROOT}/${distName}/${version}/dist.json`), { type: 'string' })
```

## Missing menu?

Unsure if I am doing something wrong, but `make publish` created `QmPvuHWJb6dpeZ6GwWGQuEPBSUcLHqCtLq2ALdRaqwn62j` which is missing menu:

> ![Screenshot_2020-10-28 IPFS Distributions](https://user-images.githubusercontent.com/157609/97470194-8df5ca00-1947-11eb-98de-a59b4e888aaf.png)

2020-10-28 17:39 UTC, olizilla commented
Many thank yous for your time @lidel I shall fix!

2020-10-28 18:02 UTC, olizilla commented
@lidel I switched the dist.js to use IPFS instead of fetching from the gateway and broke it! **and** I added in more cleaning which broke the site build. Is fixed now!

<img width="1324" alt="Screenshot 2020-10-28 at 17 53 17" src="https://user-images.githubusercontent.com/58871/97477442-8df5ca00-1947-11eb-9320-4099fdef464d.png">

> But I think we need to make it more self-contained and reproducible.

Strong agree. This is my _how the heck does dist work_ PR. Next up is reproducibuild++

2020-10-28 19:43 UTC, olizilla commented
Dist now builds in in a github workflow in 1min 23s! ✨🎷🐩
https://github.com/ipfs/distributions/pull/320/checks?check_run_id=1322838224

2020-12-09 19:49 UTC, lidel approved these changes
I re-checked to see if it will pick up `v0.8.0-rc1` added upstream and it worked as expected (detected upstream data and skipped/reused it):

```console
$ ./dist.sh add-version go-ipfs v0.8.0-rc1
WARNING: not marking pre-release go-ipfs v0.8.0-rc1 as the current version.
../../build-go.sh "go-ipfs" "github.com/ipfs/go-ipfs" "cmd/ipfs" versions
comparing versions with /ipns/dist.ipfs.io/go-ipfs/versions
skipping go-ipfs - all versions published at /ipns/dist.ipfs.i
```

I suggest we give it a try: merge this PR and then see if adding `v0.8.0-rc2` works as expected. 
That will be a safe way to test if it behaves as expected without impact on real release.

2021-01-19 18:47 UTC, jessicaschilling commented
@olizilla, do we have plans for wrapping this up or should it be iceboxed?

2021-01-20 11:27 UTC, olizilla commented
@aschmahmann pls may i have your official blessing to merge this and unblock #327

2021-01-20 14:54 UTC, aschmahmann commented
@olizilla I was hoping to test this with RC2 (probably next week 🤞) just to verify that all the outputs look as expected (i.e. build before + after the PR to verify things look right).

If you've already done that though then we can probably just merge and still check the diffs on publish to verify things look right

2021-01-20 14:56 UTC, olizilla commented
I verified it at the time of writing, and @lidel tested it out. I'm very happy to wait for your test run too tho, as it's a significant change.

2021-01-29 06:04 UTC, aschmahmann approved these changes
This is amazing! A huge thank you to @olizilla and everyone who committed, reviewed and tested this PR.

2021-01-29 06:05 UTC, merged